version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch_db
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=DkIedPPSCb
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      
  python-app:
    build: 
      context: ./app
      dockerfile: Dockerfile  # Dockerfile is directly in the app directory
    container_name: streamlit_app
    depends_on:
      - elasticsearch
    ports:
      - "8501:8501"  # Port for Streamlit
    volumes:
      - ./app:/app
    working_dir: /app
    restart: unless-stopped
